name: jbl_search
description: The unique package for three types of search(linear, binary, jump or box). And you can also see time of searching of each search. 
version: 1.0.0
repository: https://github.com/Mardonbekmelsov/jbl_search

environment:
  sdk: ^3.4.4


dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
